### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by eduardojpanzo** [jgoncalves8080/travel-app#2]
Professor José não está ser possível fazer alteração neste repositório remoto ..
acredito eu que não temos permissão..
**o que o Prof sugere?**

**Comment by jgoncalves8080** [comment]
Qual a mensagem aparece?

**Comment by eduardojpanzo** [comment]
remote: Permission to jgoncalves8080/travel-app.git denied to EduardoPanzo.
fatal: unable to access 'https://github.com/jgoncalves8080/travel-app.git/': The requested URL returned error: 403

**Comment by jgoncalves8080** [comment]
Tenta novamente, fiz um invite pra você.

**Comment by FabioJunik** [comment]
Panzo, acredito que tens que fazer uma solicitação de pull request, para isso tens que fazer o fork do projecto e renomear o repositório remoto com o caminho do repositório forked e para finalizar faz a solicitação de pull resquest

**Comment by eduardojpanzo** [comment]
Resolvido...
